-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 12:12:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `term` VARCHAR(45) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentCourse` (
  `student_course_id` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  `Course_course_id` INT NOT NULL,
  PRIMARY KEY (`student_course_id`, `Student_idStudent`, `Course_course_id`),
  INDEX `fk_StudentCourse_Student_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_StudentCourse_Course1_idx` (`Course_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_StudentCourse_Student`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentCourse_Course1`
    FOREIGN KEY (`Course_course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administartor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administartor` (
  `idAdministartor` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idAdministartor`, `Student_idStudent`),
  INDEX `fk_Administartor_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Administartor_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdminLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdminLogin` (
  `admin_login_id` INT NOT NULL,
  `admin_id` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL,
  `admin_password` VARCHAR(45) NULL,
  `Administartor_idAdministartor` INT NOT NULL,
  `Administartor_Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`admin_login_id`, `Administartor_idAdministartor`, `Administartor_Student_idStudent`),
  INDEX `fk_AdminLogin_Administartor1_idx` (`Administartor_idAdministartor` ASC, `Administartor_Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_AdminLogin_Administartor1`
    FOREIGN KEY (`Administartor_idAdministartor` , `Administartor_Student_idStudent`)
    REFERENCES `mydb`.`Administartor` (`idAdministartor` , `Student_idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentLogin` (
  `student_login_id` INT NOT NULL,
  `student_name` VARCHAR(45) NULL,
  `student_passowrd` VARCHAR(45) NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`student_login_id`, `Student_idStudent`),
  INDEX `fk_StudentLogin_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_StudentLogin_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grade` (
  `idGrade` INT NOT NULL,
  `GradeValue` VARCHAR(45) NULL,
  `Course_course_id` INT NOT NULL,
  PRIMARY KEY (`idGrade`, `Course_course_id`),
  INDEX `fk_Grade_Course1_idx` (`Course_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Grade_Course1`
    FOREIGN KEY (`Course_course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
